// Generates dist/oro-web.css from @oro/tokens.
// Every recipe is transcribed 1:1 from oro-landing's shipped CSS (the landing's
// pixels are canonical — see CLAUDE.md). Colors reference the landing's theme
// custom properties (--color-fg/bg etc.) with token-derived fallbacks, so the
// classes theme correctly inside the landing and still render standalone
// (Storybook, future consumers) without any variables defined.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { colors, withAlpha, shiftLightness } = require('@oro/tokens');

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../dist/oro-web.css');

const serif = `var(--font-serif, "Fraunces", "Cormorant Garamond", serif)`;
const sans = `var(--font-sans, "Inter", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif)`;
const sysSans = `-apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif`;
// Landing theme vars, with dark-theme token fallbacks (the landing defaults dark).
const fg = `var(--color-fg, ${colors.paper})`;
const bg = `var(--color-bg, ${colors.plum})`;
const fgLine = `var(--color-fg-line, ${withAlpha(colors.paper, '2E')})`;
const fgFaint = `var(--color-fg-faint, ${withAlpha(colors.paper, 'B3')})`;
const accent = `var(--color-accent, ${colors.gold})`;
const hoverOnDark = colors.primaryActionHoverOnDark ?? shiftLightness(colors.plum, 1.5);
const hoverTint = colors.hoverTint ?? withAlpha(colors.plum, '12');
const goldLight = shiftLightness(colors.gold, 1.2);
const ivory = colors.cream;

// Raw-palette theme vars, matching the names oro-landing emits in
// src/generated/tokens.css (see scripts/generate-tokens.mjs there). NOTE the
// deliberate naming shift on the landing: --oro-cream is token `paper`
// (#FFF9ED), --oro-paper is token `white`, --oro-ivory is token `cream`
// (#FFF2D7). Each fallback below is the exact value the variable resolves to,
// so themed consumers follow their overrides and everyone else is unchanged.
const plumDeepVar = `var(--oro-plum-deep, ${colors.plum})`; // #3A2646
const plumSoftVar = `var(--oro-plum-soft, ${shiftLightness(colors.plum, 1.25)})`; // #493058
const creamVar = `var(--oro-cream, ${colors.paper})`; // #FFF9ED
const ivoryVar = `var(--oro-ivory, ${colors.cream})`; // #FFF2D7

const css = `/* GENERATED by @oro/web scripts/build-css.mjs from @oro/tokens — do not edit.
 * Recipes are transcribed 1:1 from oro-landing's CSS; the landing's pixels are canonical. */

/* ── .oro-cta — editorial serif-italic CTA (the landing's signature button) ──
 * Sizes map to the landing originals:
 *   --compact   = .hero-cta-primary        (16px, 12x22)
 *   --standard  = .jr-subscribe            (18px, 16x26)
 *   --statement = .fcta-cta / .ins-cta     (19px, 18x28)
 *   --hero      = .hero-cta-primary--ondark(19px, 16x26, 1px border, inverse)
 *   --full      = .gs-cta                  (22px, 20x24, full width, square)
 *   --block     = .ct-send                 (20px, 18x24, full width, fixed plum/cream)
 *   --inline    = .cl-submit               (15px, transparent, plum label — inline form CTA)
 *   --pill      = .newsletter-article-cta-button
 *                                          (0.82rem, full radius, plum fill, ivory
 *                                           label, inherited font-family — the
 *                                           end-of-article / store link)
 * Color: default = surface (bg/fg follow the theme vars); add --inverse to flip. */
.oro-cta {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  border: none;
  cursor: pointer;
  font-family: ${serif};
  font-style: italic;
  letter-spacing: -0.3px;
  text-decoration: none;
  background: ${bg};
  color: ${fg};
}
.oro-cta--compact { padding: 12px 22px; font-size: 16px; }
.oro-cta--standard { padding: 16px 26px; font-size: 18px; gap: 12px; }
.oro-cta--statement { padding: 18px 28px; font-size: 19px; gap: 12px; }
.oro-cta--hero { padding: 16px 26px; font-size: 19px; gap: 12px; border: 1px solid ${fg}; }
.oro-cta--full {
  width: 100%;
  /* The original .gs-cta was a native <button> (width:100%), whose text
     centers by default; inline-flex would left-align it. */
  justify-content: center;
  border-radius: 0;
  font-weight: 400;
  font-size: 22px;
  padding: 20px 24px;
  transition: opacity 0.2s ease, transform 0.15s ease;
}
.oro-cta--block {
  width: 100%;
  justify-content: center;
  gap: 14px;
  padding: 18px 24px;
  font-size: 20px;
  /* Fixed plum/cream: this one sits on the cream letter card in both themes.
     Expressed as the landing's raw-palette vars so a theming consumer can
     override them; the fallbacks are byte-identical to the old literals. */
  background: ${plumDeepVar};
  color: ${creamVar};
  transition: opacity 150ms ease;
}
.oro-cta--block:hover:not(:disabled) { opacity: 0.92; }
.oro-cta--block:disabled { opacity: 0.6; cursor: default; }
.oro-cta--inline {
  padding: 10px 4px 10px 16px;
  gap: 8px;
  /* the original .cl-submit inherited normal tracking, not the CTA's -0.3px */
  letter-spacing: normal;
  background: transparent;
  color: ${colors.plum};
  font-size: 15px;
  transition: opacity 150ms ease;
}
.oro-cta--inline:hover:not(:disabled) { opacity: 0.75; }
/* A full-radius label pill. Transcribed from the landing's
   .newsletter-article-cta-button, which is an <a href> — Cta renders a
   <button>, so the recipe is written to be correct on either element
   (text-decoration: none comes from the .oro-cta base). The base is serif
   italic with -0.3px tracking, so this resets font-family/style/tracking.
   font-family stays 'inherit' as on the landing, where it picks up the
   article's serif — do not pin a family or the landing's pixels shift. */
.oro-cta--pill {
  display: inline-block;
  padding: 0.7rem 1.5rem;
  color: ${ivoryVar};
  background: ${plumDeepVar};
  border: 0;
  border-radius: 999px;
  font-family: inherit;
  font-style: normal;
  font-size: 0.82rem;
  font-weight: 600;
  letter-spacing: normal;
  transition: background 0.25s ease, transform 0.25s ease;
}
.oro-cta--pill:hover:not(:disabled) {
  background: ${plumSoftVar};
  transform: translateY(-1px);
}
.oro-cta--inverse { background: ${fg}; color: ${bg}; }

/* Hover/focus — the perceptible steps shipped in oro-landing #28. */
.oro-cta:hover:not(:disabled):not(.oro-cta--inverse):not(.oro-cta--full):not(.oro-cta--block):not(.oro-cta--inline):not(.oro-cta--pill) {
  background: ${hoverOnDark};
  transform: translateY(-1px);
  box-shadow: 0 6px 18px ${withAlpha(colors.plum, '59')};
}
:root[data-theme='light'] .oro-cta:hover:not(:disabled):not(.oro-cta--inverse):not(.oro-cta--full):not(.oro-cta--block):not(.oro-cta--inline):not(.oro-cta--pill) {
  background: ${hoverTint};
}
.oro-cta--inverse:hover:not(:disabled):not(.oro-cta--full) {
  background: ${ivory};
  border-color: ${ivory};
  transform: translateY(-1px);
  box-shadow: 0 0 0 1.5px ${colors.gold}, 0 8px 24px ${withAlpha(colors.ink, '59')};
}
:root[data-theme='light'] .oro-cta--inverse:hover:not(:disabled):not(.oro-cta--full) {
  background: ${colors.plum};
  box-shadow: 0 8px 24px ${withAlpha(colors.plum, '4D')};
}
.oro-cta--full:hover:not(:disabled) { opacity: 0.9; }
.oro-cta--full:active:not(:disabled) { transform: translateY(1px); }
.oro-cta:disabled { opacity: 0.32; cursor: not-allowed; }
.oro-cta:focus-visible {
  outline: 2px solid ${colors.focusRing ?? withAlpha(colors.gold, 'B3')};
  outline-offset: 2px;
}

/* ── .oro-btn — quiet in-flow utility buttons ──
 * Brand rule: NO all-caps + wide tracking anywhere (see CLAUDE.md). The
 * landing originals used tiny uppercase tracked labels; they are lowercase
 * with normal tracking here, one size up so the optical size is preserved.
 *   --quiet  = .modal-done-btn   (outline, plum-tinted)
 *   --accent = .cookie-consent-accept  (gold fill)
 *   --ghost  = .cookie-consent-decline (transparent outline on dark) */
.oro-btn {
  cursor: pointer;
  border-radius: 8px;
  font-weight: 600;
  letter-spacing: 0;
  font-size: 0.84rem;
  padding: 0.78rem 1.2rem;
  font-family: ${sysSans};
  border: none;
  transition: all 0.25s ease;
}
.oro-btn--quiet {
  width: 100%;
  padding: 0.875rem;
  font-size: 0.82rem;
  letter-spacing: 0;
  background: transparent;
  color: ${withAlpha(colors.plum, 'AD')};
  border: 1px solid ${withAlpha(colors.plum, '29')};
  border-radius: 10px;
}
.oro-btn--quiet:hover {
  border-color: rgba(238, 186, 43, 0.7);
  color: ${colors.plum};
  background: rgba(255, 255, 255, 0.28);
}
.oro-btn--accent {
  color: ${colors.plum};
  background: ${colors.gold};
  box-shadow: 0 4px 20px ${withAlpha(colors.plum, '2E')};
}
.oro-btn--accent:hover { background: ${goldLight}; }
.oro-btn--ghost {
  font-weight: 500;
  letter-spacing: 0;
  color: rgba(245, 240, 232, 0.72);
  background: transparent;
  border: 1px solid rgba(245, 240, 232, 0.14);
}
.oro-btn--ghost:hover {
  border-color: ${withAlpha(colors.gold, '59')};
  color: rgba(245, 240, 232, 0.92);
}
.oro-btn:focus-visible {
  outline: 2px solid ${colors.focusRing ?? withAlpha(colors.gold, 'B3')};
  outline-offset: 2px;
}

/* ── .oro-chip — selection chips ──
 *   default = .ct-chip  (serif italic, square-ish, light surfaces)
 *   --pill  = .gs-chip  (sans, full radius, theme surfaces) */
.oro-chip {
  padding: 6px 14px;
  background: transparent;
  border: 1px solid ${withAlpha(colors.ink, '29')};
  cursor: pointer;
  font-family: ${serif};
  font-style: italic;
  font-size: 13px;
  color: ${colors.plum};
  transition: background 150ms ease, border-color 150ms ease, color 150ms ease;
}
.oro-chip:hover { border-color: ${colors.plum}; }
.oro-chip[aria-pressed='true'], .oro-chip--selected {
  background: ${colors.plum};
  border-color: ${colors.plum};
  color: ${colors.paper};
}
.oro-chip--pill {
  border: 1px solid ${fgLine};
  background: transparent;
  color: ${fg};
  font-family: ${sans};
  font-style: normal;
  font-size: 15px;
  padding: 12px 20px;
  border-radius: 999px;
  transition: border-color 0.2s ease, background 0.2s ease, color 0.2s ease;
}
.oro-chip--pill:hover { border-color: ${fgFaint}; }
.oro-chip--pill[aria-pressed='true'] {
  background: ${accent};
  border-color: ${accent};
  color: ${bg};
}
.oro-chip:focus-visible {
  outline: 2px solid ${colors.focusRing ?? withAlpha(colors.gold, 'B3')};
  outline-offset: 2px;
}
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css);
console.log(`wrote ${out}`);
